#!/bin/bash
# Create a ribosome interval list for Picard collect RNA metrics
set -e

# INPUTS
USAGE="USAGE ${0} ALIGNMENTS ANNOTATION_GTF_GZ <OUTPUT=ribosomal.intervals_list>"
if [[ -z "${1}" ]]; then
    echo "${USAGE}" && exit 2
fi
alignments="${1}"
if [[ -z "${2}" ]]; then
    echo "${USAGE}" && exit 2
fi
annotation_gtf_gz="${2}"

# OUTPUT
if [[ -z "${3}" ]]; then
    ribosomal_il="ribosomal.intervals_list"
else
    ribosomal_il="${3}"
fi

# Add a header line
echo -e "@HD\tVN:1.4" > ${ribosomal_il}
# Add the seq dict from alignments
samtools view -H ${alignments} | grep "@SQ" >> ${ribosomal_il}
# Grep the rRNA from the annotations, format to inverval list, sort
zgrep -i rRNA ${annotation_gtf_gz} | \
    cut -f1,4,5,7,9 | \
    perl -lane '
        /gene_id "([^"]+)"/ or die "no gene_id on $.";
        print join "\t", (@F[0,1,2,3], $1)
    ' | \
    sort -k1V -k2n -k3n \
    >> ${ribosomal_il}
