#!/bin/bash
USAGE="${0} <ANNOTATION> <OUTPUT>"
# ANNOTATION  gtf gz
set -ex
if [[ -z "${1}" ]]; then
    echo "${USAGE}" && exit 2
fi
annotation="${1}"
if [[ -z "${2}" ]]; then
    echo "${USAGE}" && exit 2
fi
refflat_fn="${2}"
zcat "${annotation}" | gtfToGenePred -genePredExt /dev/stdin /dev/stdout | awk 'BEGIN {OFS="\t"} {print $12, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' > "${refflat_fn}"
