#!/bin/bash
set -e
if [[ -z "${1}" ]]; then
    echo "USAGE ${0} ANNOTATION_GZ <OUTPUT>" && exit 2
fi
annotation_fn="${1}"
if [[ -z "${2}" ]]; then
    refflat_fn="${1/\.gz$}.refflat"
    refflat_fn="${refflat_fn/\.gtf$}"
else
    refflat_fn="${2}"
fi
zcat "${annotation_fn}" | gtfToGenePred -genePredExt /dev/stdin /dev/stdout | awk 'BEGIN {OFS="\t"} {print $12, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' > "${refflat_fn}"
